name: App Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_VERSION="0.35.0" RYE_INSTALL_OPTION="--yes" bash
      - name: Install dependencies
        run: |
          source "$HOME/.rye/env"
          rye sync
      - name: Test with pytest
        run: |
          source "$HOME/.rye/env"
          mkdir -p .reports/coverage
          rye run test | tee .reports/coverage/coverage.txt
          ls -al .reports/coverage
      # - name: Publish Test Report
      #   uses: mikepenz/action-junit-report@v4
      #   if: success() || failure()
      #   with:
      #     report_paths: '**/junit/test-results.xml'
      #     github_token: ${{ github.token }}
      #     include_passed: true
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: .reports/coverage/coverage.txt
          junitxml-path: .reports/junit/test-results.xms
          github-token: ${{ github.token }}
      - name: Check the output coverage
        run: |
            echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
            echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
            echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"
            echo "Summary Report - ${{ steps.coverageComment.outputs.summaryReport }}"
        
            echo "Coverage Warnings - ${{ steps.coverageComment.outputs.warnings }}"
        
            echo "Coverage Errors - ${{ steps.coverageComment.outputs.errors }}"
            echo "Coverage Failures - ${{ steps.coverageComment.outputs.failures }}"
            echo "Coverage Skipped - ${{ steps.coverageComment.outputs.skipped }}"
            echo "Coverage Tests - ${{ steps.coverageComment.outputs.tests }}"
            echo "Coverage Time - ${{ steps.coverageComment.outputs.time }}"
            echo "Not Success Test Info - ${{ steps.coverageComment.outputs.notSuccessTestInfo }}"