name: App Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_VERSION="0.35.0" RYE_INSTALL_OPTION="--yes" bash
      - name: Install dependencies
        run: |
          source "$HOME/.rye/env"
          rye sync
      - name: Test with pytest
        run: |
          source "$HOME/.rye/env"
          rye run test-coverage 
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/junit/test-results.xml'
          github_token: ${{ github.token }}
          include_passed: true
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: .reports/coverage/coverage.xml
          junitxml-path: .reports/junit/test-results.xml
          github-token: ${{ github.token }}
      - name:
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: .reports/coverage/coverage.lcov